title: "Dali Kewara"
tagline: "An unexpected journey"
description: "A guy who lives and works as a Backend Developer in Indonesia—building useful and unexpected things, and making positive impacts for people. He loves to code and draw his own world—also has interests in art, writing and journey (traveling). He is on an unexpected journey and gonna make it simple but spectacular!"
keywords: "dali, dali kewara, dalikewara, posts, projects, website, art, writing, journey, developer, backend, software engineer"
url: "https://www.dalikewara.com"
author:
  name: "Dali Kewara"
  url: "https://www.dalikewara.com"
twitter:
  username: "dalikewara"
  card: "summary"
logo: "/assets/img/pic.jpg"
social:
  name: "Dali Kewara"
  links:
    - "https://www.twitter.com/dalikewara"
    - "https://www.facebook.com/dalikewara"
    - "https://www.linkedin.com/in/dalikewara"
    - "https://www.github.com/dalikewara"
    - "https://www.instagram.com/dalikewara"
    - "https://opensea.io/dalikewara"
    - "https://www.youtube.com/channel/UCgK0T0mxumi9uNQewd1RIwg"
google_site_verification: "Czw8BPlbSgfcKuHG56yYHEU2TPLH5TK29b80uJLX-CY"
jekyll_analytics:
  GoogleAnalytics:
    id: "UA-68907511-1"
    anonymizeIp: true
google:
  tag_manager:
    container_id: "GTM-MMH79W"
permalink: "/:categories/:year/:month/:day/:title"
plugins:
  - "jekyll-seo-tag"
  - "jekyll-analytics"
  - "jekyll-google-tag-manager"
  - "jekyll-minifier"
  - "jekyll-sitemap"
  - "jekyll-postfiles"
jekyll-minifier:
  uglifier_args:
    harmony: true
greeting:
  title: "Hello there,"
  content: "I'm <strong>Dali Kewara</strong>, a guy who lives and works as a Backend Developer in <img src='/assets/img/indonesia-flag-pixel.png'/> Indonesia—building useful and unexpected things, and making positive impacts for people.<br/><br/>I love to code and draw my own world—also have interest in art, writing and journey (traveling). I'm on an unexpected journey and gonna make it simple but spectacular! <br/><br/> <iframe src='https://github.com/sponsors/dalikewara/button' title='Sponsor dalikewara' height='35' width='116' style='border: 0;color:yellow !important'></iframe>"
job:
  title: "What am I doing in real life?"
  currentWork: "Currently, I work as a Software Engineer (Backend) for living&mdash;at least I've worked for these companies:"
  afterWorkingHours: "After working hours, sometimes I enjoy myself by watching <a href='https://www.youtube.com/results?search_query=solo+bushcraft' class='hint--bottom hint--no-animate' aria-label='Click to go'>solo bushcraft</a> contents on <img src='/assets/img/youtube-pixel.png'/> YouTube, listening <a href='https://open.spotify.com/playlist/3sQKVJHpxisbBGGtC1mA4I?si=a5610bb4d8ce4048' class='hint--bottom hint--no-animate' aria-label='Click to go'>Yorushika</a> on <img src='/assets/img/spotify-pixel.png'/> Spotify, playing <img src='/assets/img/dota2-pixel.png'/> <a href='https://steamcommunity.com/id/green_4pple' class='hint--bottom hint--no-animate' aria-label='Click to go'>Dota 2</a>, traveling, or creating projects."
footer:
  copyright: "Copyright © 2017 - 2022 Dali Kewara. All rights reserved. Proudly made with <a href='https://jekyllrb.com' class='hint--bottom hint--no-animate' aria-label='Click to go'>Jekyll</a>, hosted on <a href='https://www.netlify.com/' class='hint--bottom hint--no-animate' aria-label='Click to go'>Netlify</a>."
postSection:
  title: "Sometimes I post something&mdash;mostly in <img src='/assets/img/indonesia-flag-pixel.png'/> Bahasa&mdash;based on my thoughts,"
  latestTitle: "Sometimes I <img src='/assets/img/scroll-pixel.png'/> post something&mdash;mostly in <img src='/assets/img/indonesia-flag-pixel.png'/> Bahasa&mdash;based on my thoughts,"
  latestLimit: 5
  excerptLimit: 20
  viewMoreUrl: "/posts"
  notFoundIcon: "/assets/img/robotics-pixel.png"
projects:
  title: "I love creating projects that can help people to solve their problems,"
  latestTitle: "I love creating <img src='/assets/img/rocket-pixel.png'/> projects that can help people to solve their problems,"
  latestLimit: 5
  viewMoreUrl: "/projects"
  notFoundIcon: "/assets/img/robotics-pixel.png"
attribution:
  title: "Attribution"
  description: "Some assets you found on this website didn't created by myself. I know that making good things like that takes a lot of time and effort, so I proudly to give them an attribution to credit the creator. Because this website has a pixel vibes, I convert them to a pixel first using <a href='https://giventofly.github.io/pixelit/' class='hint--bottom hint--no-animate' aria-label='Click to go'>Pixel It</a>&mdash;if they are not pixel arts by default."
contact:
  title: "Want to know me more? find me on these platform:"
  description: "<blockquote>For professional purpose, don't hesitate to email me at <code>dalikewara[at]gmail.com</code></blockquote>"
  notFoundIcon: "/assets/img/robotics-pixel.png"
wfa:
  title: "Currently, my company allows me to Working From Anywhere <img src='/assets/img/flame-pixel.png'/><img src='/assets/img/smile-love-pixel.png'/> &mdash;until further notice"
  content: "<img src='/assets/img/pika-heart-pixel.gif'/>"