site_name: Dali Kewara
copyright: Copyright &copy; 2017 - 2025 Dali Kewara. All rights reserved.

nav:
  - 🏠 /: index.md
  - 📁 /blog:
    - blog/index.md
  - 📁 /docs:
    - Umar:
      - ecosystem/umar/index.md
  - 📖 /legal-and-license: legal-and-license.md

theme:
  name: material
  logo: assets/img/32x32_green_apple.webp
  favicon: favicon.ico
  language: en
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

extra_css:
  - assets/css/color.css
  - assets/css/base.css
  - assets/css/img.css

extra_javascript:
  - assets/js/link.js

plugins:
  - search
  - blog
  - tags
  - meta
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: table

extra:
  alternate:
    - name: English
      link: /
      lang: en
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dalikewara
      name: dalikewara on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dalikewara
      name: dalikewara on LinkedIn
    - icon: fontawesome/brands/github
      link: https://www.github.com/dalikewara
      name: dalikewara on GitHub