backend:
  name: git-gateway
  branch: master
logo_url: https://lh3.googleusercontent.com/pw/ACtC-3dBME0xNP8kojcslSG6fOJxYTgQ_30vbVGvWb2DIz0M6GFQ1DdEl7fUhruizL0uuSjQpx_3j3htACAV92-EYtbrj5bkr0zdfiWOa6z87OXt_zr9T1OkXQXoIOu2Gx3AJcAtSl7ZVbNKkTo36LJYmE9v=w900-h300-no

# Editorial workflow

publish_mode: editorial_workflow

# Media & public folder

media_folder: "content/images"
public_folder: "/images"

# Collections

collections:


  - name: "articles-blog"
    label: "Articles: Blog"
    folder: "content/articles/blog"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}


  - name: "articles-js"
    label: "Articles: JS"
    folder: "content/articles/js"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}
  

  - name: "articles-notebooks"
    label: "Articles: Notebooks"
    folder: "content/articles/notebooks"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}


  - name: "articles-php"
    label: "Articles: PHP"
    folder: "content/articles/php"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}


  - name: "articles-python"
    label: "Articles: Python"
    folder: "content/articles/python"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}


  - name: "articles-status"
    label: "Articles: Status"
    folder: "content/articles/status"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Tags", name: "Tags", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}


  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    identifier_field: "Title"
    summary: "{{filename}}.{{extension}} | {{commit_author}} - {{commit_date}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string", required: false}
      - {label: "Featured Image Url", name: "cover_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "Date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm"}
      - {label: "Save As", name: "Save_as", widget: "string", required: false}
      - {label: "Slug", name: "Slug", widget: "string", required: false}